name:                websockets-rpc
version:             0.7.0
github:              "athanclark/websockets-rpc"
license:             BSD3
author:              "Athan Clark"
maintainer:          "athan.clark@gmail.com"
copyright:           "BSD-3"
synopsis:            Simple streaming RPC mechanism using WebSockets
category:            Web

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/athanclark/sparrow-server#readme>

dependencies:
  - base >= 4.10 && < 5.0
  - aeson
  - async
  - bytestring
  - containers
  - exceptions
  - hashable
  - monad-control
  - mtl
  - QuickCheck
  - stm
  - text
  - transformers
  - unordered-containers
  - uuid
  - wai-transformers
  - websockets >= 0.12
  - websockets-simple >= 0.1.0

ghc-options:
  - -Wall
library:
  source-dirs: src

tests:
  sparrow-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - websockets-rpc
    - aeson
    - QuickCheck
    - quickcheck-instances
    - tasty
    - tasty-quickcheck
